version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - Jack-Works
  - guanbinrui
  - septs
  labels:
  - Dependencies
  ignore:
  - dependency-name: electron
    versions:
    - 9.4.0
    - 9.4.2
  - dependency-name: ini
    versions:
    - 1.3.7
